### ISSUE TITLE
Cannot save tiff file

### ISSUE THREAD

**Issue by Kugelblitz101** [mblong/hobjExample#1]
I am using QtOMA built with Qt 6.0.0 and MinGW-64bit on Windows 10 and attempting to run the batchCorrect macro. Initially the macro did not work because line 19 of batchCorrect.o2m was incompatible with the Windows Bash Shell. The script was edited by replacing line 19 with the following:
`shell ("%qmacros\getNamesInFolder-r.sh" "%q@folder\" "@ext\")`

When attempting to save the tiff file using the `satiffscaled` command, the program reports that the functionality is not implemented in QtOMA. When this command is replaced with 'satiff', the program reports that it "Could not save Tiff file" The error with `satiff` persists regardless of the name or path for the file.

**Comment by mblong** [comment]
satif @folder\/@name 
works fine for me on 5.15.1
Note however that this does not preserve the original 12-bit data, but stores the 8-bit bitmap from the last window displayed. If you want to preserve the full resolution of the data in a form readable by other programs, I'd suggest writing a csv file with 
fwdat @folder\/@name ,

Or use oma2 on a Mac, which has more features and is better tested.
